# Generated by Django 5.0.4 on 2024-04-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="prefs",
            field=models.JSONField(default={}),
        ),
    ]
