# Generated by Django 5.0.4 on 2024-04-21 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0002_domain_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="DomainStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("dimension", models.CharField(max_length=16)),
                ("member", models.CharField(max_length=16)),
                ("count", models.PositiveIntegerField()),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analytics.domain",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Report",
        ),
    ]
