# Generated by Django 5.0.4 on 2024-04-21 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("counter", "0002_alter_user_uuid"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="domaincount",
            unique_together={("user", "domain", "date", "dimension", "member")},
        ),
    ]
